### ISSUE TITLE
Usage with plm function possible?

### ISSUE THREAD

**Issue by julianjaecker** [franzmohr/prais#8] opened 2023-02-24 09:35 UTC
Dear Franz,

thank you for the great package. I am doing a fixed effects estimation and intend to use the Prais_Winsten estimator to account for the serial correlation of my model. I have set up both a Least Squared Dummy Variable Model of type lm and a plm model. Both have the exact same estimates for my independent variables (see code below):

LSDV_model <- lm(EPS_relative_lead  ~ share_femalemin + avg_agemin  + GDPlog + green_parl + Schmidt_Index + factor (Country) + factor (Year), data=data_OECD.p_noNA)

FE_model <- plm(EPS_relative_lead ~ share_femalemin  + avg_agemin + GDPlog + green_parl + Schmidt_Index, data=data_OECD.p_noNA,effect = "twoways", model = "within")_

Yet, when using prais_winsten, I receive completely different results depending on whether I use my LSDV_model or my FE_model. I was therefore wondering, whether the usage of prais_winsten basen on a plm model was even possible or whether this is an error?

Thanks for your help!

**Comment by franzmohr** [comment] 2023-02-25 09:53
Hi Julian! Thanks for using the package! And yes, since version 1.1 it supports panel regression. An explanation on how to use the package with panel data can be found in the README file here on GitHub. But I probably should add a vignette to the package. Regarding the results, I did quite intensive testing of the package by making sure that the results are equal to the output from Stata. In your case I could offer to the same if you feel comfortable sharing your data. Best, Franz

**Comment by julianjaecker** [comment] 2023-02-25 10:54
Dear Franz,

 

thanks for your help. I have my dataframe attached to this e-mail, so feel free to test it. My DV is “EPS_relative_lead” and my IVs are “share_femalemin” and “avg_agemin”. Controls are GDPlog, green_parl and Schmidt_index. I have also included factors for Country and Year. 

The code I used for the Prais-Winsten estimation is:

 

prais_winsten (EPS_relative_lead ~ share_femalemin + avg_agemin + Schmidt_Index + green_parl + GDPlog + factor (Country) + factor (Year), data = data_OECD_noNA, index = c("Country","Year"), panelwise = TRUE, rhoweight = "T1")

 

I was furthermore wondering whether the prais_winsten command would also work using a model of class ‘plm’.

 

Happy to receive your comments and thanks a lot for your help.

Best, Julian

 

 

 

Von: Franz Mohr ***@***.***> 
Gesendet: Samstag, 25. Februar 2023 10:54
An: franzmohr/prais ***@***.***>
Cc: julianjaecker ***@***.***>; Author ***@***.***>
Betreff: Re: [franzmohr/prais] Usage with plm function possible? (Issue #8)

 

Hi Julian! Thanks for using the package! And yes, since version 1.1 it supports panel regression. An explanation on how to use the package with panel data can be found in the README file here on GitHub. But I probably should add a vignette to the package. Regarding the results, I did quite intensive testing of the package by making sure that the results are equal to the output from Stata. In your case I could offer to the same if you feel comfortable sharing your data. Best, Franz

**Comment by franzmohr** [comment] 2023-02-25 11:08
Thanks, but I did not receive the attachment. Please send it to prais.r@outlook.com

**Comment by franzmohr** [comment] 2023-02-25 13:51
Just checked

1) I had to take Italy out of the sample, because the observation for 2012 is missing.
2) With the reduced sample I was able to replicate your results and can confirm that the coefficients are changing drastically. And in R
```
pw <- prais_winsten(EPS_relative_lead ~ share_femalemin + avg_agemin + GDPlog + green_parl + Schmidt_Index,
                    data = data,
                    index = c("Country","Year"),
                    twostep = TRUE, panelwise = TRUE, rhoweight = "T1") 
```
gives the same estimates as in Stata
```
xtpcse EPS_relative_lead share_femalemin avg_agemin GDPlog green_parl Schmidt_Index, correlation(ar1) pairwise

```
3) Regarding the question if plm objects can be used as input I opened a separate issue.

Since it doesn't seem to be a package issue, I will close this issue.

**Closed as completed by franzmohr** 2023-02-25 13:51 UTC
